# Generated by Django 5.0.7 on 2024-07-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_export_celery", "0012_alter_exportjob_queryset"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="processing_finished_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Have we finished processing the file? If so when?",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="processing_finished_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Have we finished processing the file? If so when?",
            ),
        ),
    ]
