# Generated by Django 5.2.8 on 2025-11-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("import_export_celery", "0012_alter_exportjob_id_alter_importjob_id"),
        ("import_export_celery", "0013_exportjob_processing_finished_at_and_more"),
    ]

    operations = []
